"""Pydantic contracts for AtlasCore foundation stage.

Minimal, explicit schemas including stable IDs, timestamps, schema_version,
validation_status, and provenance metadata.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any, Literal
from uuid import UUID, uuid4
from datetime import datetime, timezone

from pydantic import BaseModel, Field


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


class ProvenanceLink(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    artifact_id: UUID
    action: str
    actor: str
    ts: datetime = Field(default_factory=_now_utc)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class BaseSchema(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    ts: datetime = Field(default_factory=_now_utc)
    schema_version: int = 1
    validation_status: Literal["UNKNOWN", "VALID", "INVALID"] = "UNKNOWN"
    provenance: List[ProvenanceLink] = Field(default_factory=list)


class ValidationResult(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    rules_run: List[str]
    passed: bool
    failures: Optional[List[str]] = None
    ts: datetime = Field(default_factory=_now_utc)
    provenance: List[ProvenanceLink] = Field(default_factory=list)


class SourceRecord(BaseSchema):
    source_id: str
    payload_ref: str


class RawDocument(BaseSchema):
    body_ref: str
    format: str


class CleanDocument(BaseSchema):
    derived_from: UUID
    normalized_fields: Dict[str, Any]
    validation_result: Optional[ValidationResult] = None


class CanonicalEntity(BaseSchema):
    type: str
    attributes: Dict[str, Any]
    canonical_sources: List[UUID]


class DetectedEvent(BaseSchema):
    event_type: str
    participants: List[UUID]
    evidence_refs: List[UUID]
    event_ts: datetime


class RelationshipEdge(BaseSchema):
    from_id: UUID
    to_id: UUID
    type: str
    evidence_refs: List[UUID]
    ontology_version: int


class Signal(BaseSchema):
    source_refs: List[UUID]
    metric: str
    evidence: List[UUID]
    validated: Optional[ValidationResult] = None


class Prediction(BaseSchema):
    model_version: UUID
    input_signal_refs: List[UUID]
    prediction_ts: datetime
    status: Literal["DRAFT", "VALIDATED", "REJECTED"] = "DRAFT"
    # Note: prediction outputs must not be generated by the foundation agent
    # unless validated signals and model approvals exist.


class FeedbackRecord(BaseSchema):
    related_id: UUID
    feedback_type: str
    payload: Dict[str, Any]


class ModelVersion(BaseSchema):
    name: str
    version: str
    created_ts: datetime = Field(default_factory=_now_utc)
    metadata: Dict[str, Any] = Field(default_factory=dict)


__all__ = [
    "BaseSchema",
    "ProvenanceLink",
    "ValidationResult",
    "SourceRecord",
    "RawDocument",
    "CleanDocument",
    "CanonicalEntity",
    "DetectedEvent",
    "RelationshipEdge",
    "Signal",
    "Prediction",
    "FeedbackRecord",
    "ModelVersion",
]
